#pragma once
typedef enum {
    SUCCESS = 0,

    ERROR_NULL_POINTER = 1,
    ERROR_INVALID_ARGUMENT = 2,
    ERROR_OUT_OF_MEMORY = 3,
    ERROR_FILE_NOT__FOUND = 4,
    ERROR_INVALID_FILE_FORMAT = 5,
    ERROR_INVALID_VALUE = 6,


    DICT_ERROR_INVALID_WORD = 100,
    DICT_ERROR_DUPLICATE_WORD = 101,
    DICT_ERROR_WORD_TOO_SHORT = 102,
    DICT_ERROR_WORD_TOO_LONG = 103,


    FIELD_INVALID_COORDINATES = 200,
    FIELD_INVALID_LETTER = 201,
    FIELD_INVALID_CELL = 202,
    FIELD_CELL_OCCUPIED = 203,
    FIELD_CELL_EMPTY = 204,
    FIELD_CELL_NOT_CONNECTED = 205,
    FIELD_WORD_ALREADY_EMPTY = 206,


    GAME_INVALID_WORD = 300,
    GAME_WORD_EMPTY = 301,
    GAME_WORD_DOESNT_CONTAIN_LETTER = 302,
    GAME_WORD_USED = 303,
    GAME_INVALID_ID = 304,
    GAME_INVALID_TIME = 305,
    GAME_INVALID_DIFFICULTY = 306,
    GAME_INVALID_FIRST_PLAYER = 307,
    GAME_LETTER_IS_MISSING = 308, //when a player tries to select a word before placing a letter
    GAME_LOW_SCORE = 309, //for adding to leaderboard


    AI_NO_MOVES_FOUND = 400,
    AI_TIMEOUT = 401,
    AI_THREAD_ERROR = 402,


    SDL_ERROR = 500,
} StatusCode;

typedef enum {
    MOVE_FOUND,
    TIME_OUT_AND_MOVE_FOUND,
    TIME_OUT_AND_MOVE_NOT_FOUND,
    MOVE_NOT_FOUND
} SearchCode;